# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: nutriapp-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nutriapp_user
      POSTGRES_PASSWORD: nutriapp_password
      POSTGRES_DB: nutriapp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
